### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by VolkerH** [TAdeJong/LEEM-analysis#3]
Hi, 

I don't have a twitter account (just read there sometimes), so just wanted to say thanks for this hint through a Github issue.
https://twitter.com/TobiasAdeJong/status/1466719789280382977

I cross-referenced to your notebook with a link in the  readme of my repo https://github.com/VolkerH/DaskFusion as I think it may be very useful. We may also need to optimize the tile positions, so this will come in handy,

**Comment by TAdeJong** [comment]
Hi @VolkerH,

Nice to hear it might be useful! And thank you for cross-referencing :-)

Although we are using this code in "production" (well..., science) internally in our research group, I am very aware that it is rough around the edges. So if any challenges arise, or if you have feedback/suggestions for improvement, please reach out, as I would be happy to think along, help and improve!

**Comment by VolkerH** [comment]
Thanks, I will  probably revisit this topic next year. Currently, if we want to do fine-adjustment of the tiles, we use Big Stitcher (Fiji). 
Would like to go to a full python solution.
Will close this for now.
